# This file is part of John Casey's public-ansible repository.

# This is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This software is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this software.  If not, see <https://www.gnu.org/licenses/>.

---
- name: "install Docker"
  yum:
    name: "{{ items }}"
    state: present
  notify: start-enable docker
  vars:
    items:
    - firewalld
    - docker
    - python-docker-py

- name: "ensure firewalld and docker are running"
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - firewalld
    - docker

- name: "modify Docker to listen on port"
  template:
    src: templates/docker.j2
    dest: /etc/sysconfig/docker
    owner: root
    group: root
    mode: 0644
  notify: restart docker
