# This file is part of John Casey's public-ansible repository.

# This is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This software is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this software.  If not, see <https://www.gnu.org/licenses/>.

---
- name: copy klipper make config
  copy:
    src: 'files/dot-config'
    dest: /home/pi/klipper/.config
    owner: pi
    group: pi
    mode: 0755

- name: build klipper MCU firmware
  command: make
  args:
    chdir: /home/pi/klipper

- name: stop klipper service
  service:
    name: klipper
    state: stopped

- name: flash MCU
  command: "make flash FLASH_DEVICE={{ mcu_port }}"
  args:
    chdir: /home/pi/klipper

- name: stop klipper service
  service:
    name: klipper
    state: restarted

